version: 1.0.{build}
image: macos-sonoma  # Use macOS Sonoma image (or the latest available)

install:
  - brew update
  - brew install python  # Ensure Python is installed
  - python3 -m venv venv  # Create a Python virtual environment
  - source venv/bin/activate  # Activate the virtual environment
  - pip install --upgrade pip  # Upgrade pip
  - pip install torrentp  # Install the 'torrentp' library

before_build:
  - torrentp download "path_to_your_torrent_file.torrent"  # Use torrentp to download the torrent

artifacts:
  - path: build_output/  # Specify path to store output or logs
    name: Build Artifacts
