version: 1.0.{build}
image: Ubuntu

branches:
  only:
    - Sera


build_script:
  - bash: |
      # Setup test files
      mkdir -p files/subfolder
      echo "Root file" > files/root.txt
      echo "Nested file" > files/subfolder/nested.txt

      # Install Filen CLI globally
      npm install -g @filen/cli

      # Upload all files recursively using Filen CLI
      find files -type f | while read file; do
        cloud_path=$(echo "$file" | sed 's|^files/||')
        echo "Uploading $file to $cloud_path..."
        filen --email=sukiwaterson@gmail.com --password=Kennyboo@25 upload "$file" "/"
      done
