version: 1.0.{build}
image: macos-sonoma

environment:
  PYTHON_VERSION: "3.9"  # You can specify the Python version here

install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install torrentp
  - brew install python@3.9
  - brew install libtorrent

script:
  # Download the torrent using torrentp
  - python3 -c "import torrentp; torrentp.download('magnet:?xt=urn:btih:52F190627CAFD84D92444768ACC9F74D3C03C225&dn=Bud Abbott Lou Costello Meet the Killer Boris Karloff (1949)&tr=udp://open.demonii.com:1337/announce&tr=udp://tracker.openbittorrent.com:80&tr=udp://tracker.coppersurfer.tk:6969&tr=udp://glotorrents.pw:6969/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://torrent.gresille.org:80/announce&tr=udp://p4p.arenabg.com:1337&tr=udp://tracker.leechers-paradise.org:6969', './downloads')"

artifacts:
  - path: ./downloads/*.torrent
    name: downloaded_torrent
    type: zip
