version: 1.0.{build}
image: Ubuntu

branches:
  only:
    - Sera

install:
  - sudo apt install -y nodejs npm curl
  - npm install -g webtorrent-cli
  - mkdir -p downloads

build_script:
  - |
      echo "Starting torrent download..."
      npx webtorrent download "magnet:?xt=urn:btih:5A54EDD6ED47D9CA7A7651CC0AB85744C93D8691&dn=Klaus-Jurgen%20E.%20Encyclopedic%20Dictionary%20of%20Landscape%20and%20Urban%20Planning...2010&tr=udp://tracker.bittor.pw:1337/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://tracker.dler.org:6969/announce&tr=udp://open.stealth.si:80/announce&tr=udp://tracker.torrent.eu.org:451/announce&tr=udp://exodus.desync.com:6969/announce&tr=udp://open.demonii.com:1337/announce" --out downloads --quiet

      echo "Uploading files to Pixeldrain..."

      find downloads -type f | while read file; do
        echo "Uploading $file..."
        curl -T "$file" -u :8ec6f000-e8d1-403d-820b-4324a6a68869 https://pixeldrain.com/api/file/
      done
