version: 1.0.{build}

# Set Ubuntu as the image for the pipeline
image: Visual Studio 2019  # Or another available Ubuntu version

# Define which branches to build
branches:
  only:
    - main

# Install dependencies
install:

  - ps: |
      # Install cmake and git if not available
      choco install cmake git -y
      # Clone libtorrent repository
      git clone https://github.com/arvidn/libtorrent.git
      cd libtorrent
      git checkout v2.0.7
      # Build libtorrent
      python setup.py install --user
  # Update the package list and install necessary dependencies
  - pip install python-libtorrent
  - pip install torrentp   # If torrentp is available in APT
  # Alternatively, if torrentp is a Python package, use pip:
  # - pip3 install torrentp

# Run commands after the repository is cloned (using `cmd` for shell commands)
# Command to download files via torrent (using torrentp):
  - cmd: torrentp <your-torrent-file>.torrent  # Replace with your actual torrent file name
