version: 1.0.{build}
image: Ubuntu

branches:
  only:
    - Sera

install:
  - sudo apt install -y nodejs npm curl
  - npm install -g webtorrent-cli

before_build:
  # Replace with your magnet link or .torrent URL
  - mkdir downloads
  - npx webtorrent download "magnet:?xt=urn:btih:B827925D3E6D87A212EEEAE2005ECDD6EA2B4763&dn=PC%20Gamer%20USA%20-%20August%202025&tr=udp://tracker.bittor.pw:1337/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://tracker.dler.org:6969/announce&tr=udp://open.stealth.si:80/announce&tr=udp://tracker.torrent.eu.org:451/announce&tr=udp://exodus.desync.com:6969/announce&tr=udp://open.demonii.com:1337/announce" --out downloads --quiet
  # Upload all files in downloads/ to PixelDrain
  - |
    for file in downloads/*; do
      if [ -f "$file" ]; then
        echo "Uploading $file to PixelDrain..."
        curl -X POST https://pixeldrain.com/api/file \
          -F "file=@$file" \
          -H "Authorization: Bearer 8ec6f000-e8d1-403d-820b-4324a6a68869"

build: on

after_build:
      fi
    done
