version: 1.0.{build}
image: Ubuntu

# Define which branches to build
branches:
  only:
    - Sera

install:
  - sudo apt update && sudo apt install rtorrent -y 

before_build:
  - rtorrent "magnet:?xt=urn:btih:EBB2762380EF680226EFF23324FA84647E7FFD7B&tr=udp%3A%2F%2Ftracker.bitsearch.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.moeking.me%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&dn=%5BBitsearch.to%5D+Lost+In+Alaska+(1952)+%5B1080p%5D+%5BBluRay%5D+%5BYTS.MX%5D"
after_build:
  - echo "Torrent download complete"

 
