version: 1.0.{build}

# Set Ubuntu as the image for the pipeline
image: Ubuntu-20.04  # Or another available Ubuntu version

# Define which branches to build
branches:
  only:
    - master
    - production

# Install dependencies
install:
  # Update the package list and install necessary dependencies
  - sudo apt-get update
  - sudo apt-get install -y python3 python3-pip
  - sudo apt-get install -y torrentp   # If torrentp is available in APT
  # Alternatively, if torrentp is a Python package, use pip:
  # - pip3 install torrentp

# Run commands after the repository is cloned (using `cmd` for shell commands)
before_build:
  - echo "Preparing to download file with torrentp"

# Command to download files via torrent (using torrentp)
build:
  - torrentp <your-torrent-file>.torrent  # Replace with your actual torrent file name
