version: 1.0.{build}

# Set Ubuntu as the image for the pipeline
image: Visual Studio 2019  # Or another available Ubuntu version

# Define which branches to build
branches:
  only:
    - main

# Install dependencies
install:
  # Update the package list and install necessary dependencies
  - apt-get update
  - sudo apt-get install -y python3 python3-pip
  - pip install torrentp   # If torrentp is available in APT
  # Alternatively, if torrentp is a Python package, use pip:
  # - pip3 install torrentp

# Run commands after the repository is cloned (using `cmd` for shell commands)
# Command to download files via torrent (using torrentp):
  - cmd: torrentp <your-torrent-file>.torrent  # Replace with your actual torrent file name
