version: 1.0.{build}

image: macos-sonoma  # Use macOS image (if supported)

# The steps for your build pipeline
install:
  # Install Homebrew if it is not already installed (to install Python)
  - brew update
  - brew install python
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install --upgrade pip
  - pip install torrentp  # Install your dependencies (including torrentp)

build:
  # Any commands to build or execute your torrentp processing script
  - source venv/bin/activate
  - torrentp --link "magnet:?xt=urn:btih:52F190627CAFD84D92444768ACC9F74D3C03C225&dn=Bud Abbott Lou Costello Meet the Killer Boris Karloff (1949)&tr=udp://open.demonii.com:1337/announce&tr=udp://tracker.openbittorrent.com:80&tr=udp://tracker.coppersurfer.tk:6969&tr=udp://glotorrents.pw:6969/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://torrent.gresille.org:80/announce&tr=udp://p4p.arenabg.com:1337&tr=udp://tracker.leechers-paradise.org:6969"  # Replace with your actual script
