version: 1.0.{build}

image: Visual Studio 2019

# Define which branches to build
branches:
  only:
    - main

environment:
  QT_QPA_PLATFORM: minimal

# Install dependencies
install:
  -  apt update
  -  apt install -y qbittorrent-nox  # Install qBittorrent-nox

# Example: Start qBittorrent-nox in the background to download the magnet link
before_build:
  - echo "Starting qBittorrent-nox in background..."
  - nohup qbittorrent-nox &  # Start qBittorrent-nox without UI in background
  - sleep 5  # Wait for qBittorrent to start
  - echo "Downloading torrent using magnet link..."
  # Replace the magnet link with your actual magnet link
  - qbittorrent-nox --add-magnet "magnet:?xt=urn:btih:YOUR_MAGNET_HASH_HERE" --max-upload-rate 0 --seeding-time 0

# Wait for download to complete (you may need to adjust this based on your download time)
after_build:
  - echo "Waiting for download to finish..."
  - sleep 120  # Adjust the sleep time based on your file size and expected download time

# Specify which files/folders you want to save as build artifacts
artifacts:
  - path: ./downloaded_file  # Specify the path to the downloaded file
    name: mydownload
