version: 1.0.{build}

image: ubuntu-latest

install:
  - sudo apt-get update
  - sudo apt-get install -y python3-pip
  - sudo apt-get install -y torrentp

script:
  - pip3 install torrentp
  - torrentp <your-torrent-file>.torrent
