version: 1.0.{build}
image: Ubuntu

branches:
  only:
    - Sera

build_script:
  - bash: |
      mkdir -p files/subfolder
      echo "Root file" > files/new.txt
      echo "Nested file" > files/subfolder/nested.txt

      echo "Uploading all files in files/ recursively..."
      find files -type f | while read file; do
        echo "Uploading $file..."
        curl -T "$file" -u :8ec6f000-e8d1-403d-820b-4324a6a68869 https://pixeldrain.com/api/file/
      done
