name: Torrent Download

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Deluge
      run: |
        sudo apt update
        sudo apt install -y deluged deluge-web deluge-console

    - name: Run Deluge Daemon
      run: |
        # Start the Deluge daemon in the background
        deluged &
        sleep 10  # Wait for the Deluge daemon to start

    - name: Configure No Seed
      run: |
        deluge-console config -s seeding_time 0
        echo "Set seeding_time to 0 to disable seeding."

    - name: Add Torrents
      run: |
        # Add the magnet link as needed
        deluge-console add "magnet:?xt=urn:btih:34F2A1FA5CD593C394C6E5B5B83B92A7165EA9A9&dn=Learn+Python+In+A+Week+And+Master+It&tr=udp%3A%2F%2Fopen.tracker.cl%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2F9.rarbg.com%3A2810%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969%2Fannounce"
        
        # If you have .torrent files in the 'torrents' directory
        for torrent in torrents/*.torrent; do
          if [ -f "$torrent" ]; then
            echo "Adding torrent: $torrent"
            deluge-console add "$torrent"
          fi
        done

    - name: Stop Deluge Daemon
      run: |
        # Properly stop the Deluge daemon
        deluge-console quit
